

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      service: orders-service
      env: ${ENV:dev}


logging:
  level:
    root: INFO
    com.ferrovial: DEBUG
    io.opentelemetry: DEBUG
    com.azure.monitor: DEBUG
    com.azure.monitor.opentelemetry: DEBUG

spring:
  application:
    name: orders-service